<div class="row">
    <div class="col-md-10">
        <form class="form-horizontal" method="post" role="form">
            <div class="form-group <? if(!empty($loginError)) echo 'has-error' ?>">
                <label class="col-sm-2 control-label" for="inputLogin">Login</label>
                <div class="col-sm-4">
                    <input type="text" name="login" class="form-control" id="inputLogin" value="<? if(!empty($login)) echo $this->escapeHtml($login) ?>" autofocus="true">
                    <? if(!empty($loginError)): ?>
                    <span class="help-block">User not found</span>
                    <? endif; ?>
                </div>
            </div>
            <div class="form-group <? if(!empty($pwdError)) echo 'has-error' ?>">
                <label class="col-sm-2 control-label" for="inputPassword">Password</label>
                <div class="col-sm-4">
                    <input type="password" class="form-control" name="password" id="inputPassword">
                    <? if(!empty($pwdError)): ?>
                    <span class="help-block">Wrong password</span>
                    <? endif; ?>
                </div>
            </div>
            <? if(!$mobile): ?>
            <div class="form-group <? if(!empty($captchaError)) echo 'has-error' ?>">
                <label class="col-sm-2 control-label" for="inputCaptcha"><img src="/auth/captcha/"></label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="captcha" id="inputCaptcha">
                    <? if(!empty($captchaError)): ?>
                    <span class="help-block">Wrong code</span>
                    <? endif; ?>
                </div>
            </div>
            <? endif; ?>
            <div class="form-group">
                <div class="col-sm-offset-2  col-sm-4">
                    <button type="submit" class="btn btn-default">Sign in</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-2">
        <div class="panel panel-default">
            <div class="panel-heading">USD</div>
            <div class="panel-body">
                Sell &ndash; <?= round($rates['usd>rub'], 2) ?> Rub<br>
                Buy &ndash; <?= round(1 / $rates['rub>usd'], 2) ?> Rub<br>
            </div>
        </div>
    </div>
</div>

