<!DOCTYPE html>
<html>
    <head>
        <title>PHDays iBank</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/css/index.css" rel="stylesheet" media="screen">

        <script src="/js/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div id="wrap">

            <header class="overview jumbotron">

                <div class="container">
                    <div class="pull-right" style="margin-top: 20px;">
                        <a class="btn btn-success btn-lg" href="/index/switchInterface/">
                            <span class="glyphicon glyphicon-repeat"></span> Switch to mobile version
                        </a>
                    </div>
                    <h1>PHDays iBank Pro</h1>
                    <p>
                        Simple and secure
                    </p>
                </div>
            </header>
            <div class="container">
                <?= $content ?>
            </div>

            <div id="push"></div>
        </div>

        <div id="footer">
            <div class="container">
                <p class="muted credit">
                    &copy; 2014 PHDays iBank
                </p>
            </div>
        </div>
    </body>
</html>